In [2]:
import rasterio
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [3]:
cwd = os.getcwd()
images_folder = '../dataset_1'

all_dfs = []

for image_path in os.listdir(images_folder):
    if not image_path.endswith('.tif'):
        continue

    date = image_path.split('_')[-1].split('.')[0]

    with rasterio.open(os.path.join(images_folder, image_path)) as src:
        band_names = [
            src.descriptions[i] if src.descriptions[i] else f'Band_{i+1}'
            for i in range(src.count)
        ]

        # Get dimensions
        rows, cols = src.height, src.width

        # Create a grid of pixel indices
        col_indices, row_indices = np.meshgrid(np.arange(cols), np.arange(rows))

        # Flatten them
        rows_flat = row_indices.flatten()
        cols_flat = col_indices.flatten()

        # Read all bands into an array [bands, rows, cols]
        data = src.read()
        num_bands = data.shape[0]

    # Build dict using grid indices
    data_dict = {
        'row': rows_flat,
        'col': cols_flat,
        'date': date
    }

    # add band values
    for b in range(num_bands):
        data_dict[band_names[b]] = data[b].flatten()

    df = pd.DataFrame(data_dict)
    all_dfs.append(df)

big_df = pd.concat(all_dfs, ignore_index=True)

csv_path = 'dataset_1_pixels_grid_indices.csv'
big_df.to_csv(csv_path, index=False)
print(f"CSV file saved to {csv_path}")

CSV file saved to dataset_1_pixels_grid_indices.csv

AttributeError: 'float' object has no attribute 'sort_values'

In [ ]:
big_df

,row,col,date,pm25_today,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,frp,elevation,pm25_change
1127228,10,36,2019-03-21,227.353088,1.046482,0.416786,285.037048,298.653259,92604.609375,1.826550e-09,3780.342285,888.0,-3.517632
1127231,10,39,2019-03-21,222.442123,0.807590,0.252601,282.486084,298.812103,91314.984375,1.826550e-09,2996.983398,984.0,1.017855
1127275,11,39,2019-03-21,211.877686,0.827773,0.047279,282.933441,298.578461,91307.570312,1.826550e-09,2840.593994,962.0,7.335114
1127184,9,36,2019-03-21,229.115036,1.166803,0.488197,285.110291,298.008392,92153.484375,1.826550e-09,2502.010742,834.0,2.016958
1127183,9,35,2019-03-21,180.864243,1.224745,0.400713,285.944336,298.910095,93295.109375,1.826550e-09,2300.299561,685.0,7.927052
1127166,9,18,2019-03-21,142.507233,1.081435,-0.672570,283.334473,297.810150,91494.609375,1.826550e-09,1502.535400,826.0,47.932182
1127182,9,34,2019-03-21,98.334557,1.046238,0.273068,284.381775,299.145203,92440.445312,1.826550e-09,1460.143799,732.0,1.592204
1127274,11,38,2019-03-21,205.142853,0.662856,0.128700,283.585449,299.109863,92167.656250,1.826550e-09,1428.339722,906.0,11.687056
1128068,29,40,2019-03-21,43.385052,0.757379,0.159014,290.435791,300.505463,95996.906250,1.826550e-09,1409.118896,382.0,29.775381
1127585,18,41,2019-03-21,71.392570,0.163548,0.447059,288.200531,300.760681,94993.609375,0.000000e+00,1140.954468,620.0,148.328232
1127012,5,40,2019-03-21,194.781097,1.063694,0.769569,282.229095,298.044678,91010.320312,1.826550e-09,1062.965454,873.0,27.732573
1127402,14,34,2019-03-21,121.920433,0.638808,0.439532,285.500336,299.651855,93624.281250,1.826550e-09,1020.050232,728.0,112.961693
1127165,9,17,2019-03-21,121.671417,0.978367,-0.751549,282.981628,297.585449,91254.320312,1.826550e-09,1005.815308,760.0,69.971962
1127141,8,37,2019-03-21,219.134811,0.909438,0.628741,283.172058,298.079773,91371.609375,1.826550e-09,985.657959,828.0,2.488194
1127056,6,40,2019-03-21,211.924988,1.132867,0.789466,282.139160,298.014893,90722.906250,1.826550e-09,985.236694,944.0,8.022170
1127033,6,17,2019-03-21,79.002502,0.816176,-0.810184,283.135986,297.261475,90968.906250,1.826550e-09,875.143738,854.0,8.013790
1127269,11,33,2019-03-21,162.057907,0.635960,0.119545,283.393066,298.701599,91550.734375,1.826550e-09,873.490906,914.0,-32.536503
1126968,4,40,2019-03-21,187.399231,0.987034,0.567746,282.783142,298.413177,91598.359375,1.826550e-09,818.905151,832.0,35.134689
1127181,9,33,2019-03-21,113.772568,0.853774,0.159828,283.183533,298.667480,91449.859375,1.826550e-09,808.171997,997.0,-23.003628
1127232,10,40,2019-03-21,222.266388,1.201186,0.136228,281.589294,297.660400,89603.156250,1.826550e-09,673.224243,1050.0,-4.566144

,lon,lat,date,pm25_today,u_wind_10m,v_wind_10m,dew_temp_2m,temp_2m,surf_pressure,precip_sum,frp,elevation,pm25_change
0,339524.446919,2.343275e+06,2022-12-27,13.625057,1.294254,0.312046,280.22186,287.84830,86948.180,8.523463e-07,0.0,1360.0,11.219316
1,350656.395999,2.343275e+06,2022-12-27,12.278015,1.371728,0.206333,281.88910,289.22437,89050.055,8.523463e-07,0.0,1189.0,13.676927
2,361788.345078,2.343275e+06,2022-12-27,11.339845,1.437077,0.102919,282.60867,289.81810,90361.140,8.523463e-07,0.0,975.0,14.504555
3,372920.294157,2.343275e+06,2022-12-27,9.915960,1.468449,0.009372,281.99050,289.51108,89793.840,8.523463e-07,0.0,1005.0,16.018063
4,384052.243237,2.343275e+06,2022-12-27,8.805679,1.376245,-0.047940,281.41156,289.73672,89388.680,8.523463e-07,0.0,1059.0,16.780613
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3093723,773670.461013,1.864601e+06,2020-04-25,17.682688,-1.642119,-0.437352,291.00684,295.40652,93246.490,2.154696e-03,0.0,870.0,4.386584
3093724,784802.410093,1.864601e+06,2020-04-25,17.028658,-1.351551,-0.424291,291.51886,295.47000,94694.160,3.074872e-03,0.0,673.0,4.523907
3093725,795934.359172,1.864601e+06,2020-04-25,16.857937,-1.055327,-0.416356,291.63696,295.43225,95401.950,3.809440e-03,0.0,819.0,5.113071
3093726,807066.308251,1.864601e+06,2020-04-25,17.566666,-0.833444,-0.651749,291.53873,296.57360,96833.530,3.523830e-03,0.0,332.0,2.577330
3093727,818198.257331,1.864601e+06,2020-04-25,18.701242,-0.628325,-0.941503,291.20500,297.86438,97861.120,3.014493e-03,0.0,339.0,-0.117201